language: python
sudo: false
# Credit: Original .travis.yml lifted from PyQtGraph lifted from VisPy

# Here we use anaconda for 2.6 and 3.3, since it provides the simplest
# interface for running different versions of Python. We could also use
# it for 2.7, but the Ubuntu system has installable 2.7 Qt4-GL, which
# allows for more complete testing.
notifications:
  email: false

virtualenv:
  system_site_packages: true

env:
  - PYTHON=3.6 QT=pyqt5 TEST=standard

before_install:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O anaconda.sh
  - chmod +x anaconda.sh
  - ./anaconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda install coverage --yes
  - conda install av -c conda-forge
  - echo ${QT}
  - echo ${TEST}
  - echo ${PYTHON}
  - conda install opencv --yes;

  - which python
  - python --version
  - pwd
  - ls

  - pip install pytest-xdist # multi-thread py.test
  - pip install pytest-cov # add coverage stats
  - pip install coveralls
  - pip install coverage
  - pip install .

before_script:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
 - pytest --cov=stytra

after_success:
 - coveralls