language: python
sudo: false
# Credit: Original .travis.yml lifted from PyQtGraph lifted from VisPy

# Here we use anaconda for 2.6 and 3.3, since it provides the simplest
# interface for running different versions of Python. We could also use
# it for 2.7, but the Ubuntu system has installable 2.7 Qt4-GL, which
# allows for more complete testing.
notifications:
  email: false

cache:
  directories:
    - $HOME/mc

env:
  - PYTHON=3.7 QT=pyqt5 TEST=standard

services:
    - xvfb

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda env create -f environment.yml
  - source activate stytra_env
  - echo ${QT}
  - echo ${TEST}
  - echo ${PYTHON}
  - hash -r

  - which python
  - python --version
  - pwd
  - ls
  - pip install pytest-xdist # multi-thread py.test
  - pip install pytest-cov
  # add coverage stats
  - pip install .

before_script:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
 - pytest

after_success:
  - pip install coveralls --upgrade  # add another coverage integration service
  - coveralls

  - pip install Sphinx==3.0.3
  - pip install sphinx_rtd_theme==0.4.3
  - pip install sphinxcontrib-bibtex
  - cd docs
  - sphinx-apidoc ../stytra -o ./build/doctrees
  - make html
  - cd ..


deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    user: __token__
    password:
      secure: DGTQVhfqKA5+isv2KA92yr6NsLv2g4o8uz+LmsErNKE7uZIkJjx0GITMdHcpc4fQCHir8EvZGVNek+8NypNWxop3lxb+BSurT8Gq7w8TZTC+hdV8bU/NllJ0qaYUUcCKIbxztsgFH7x35K2xB9pHAxj2GE1BaaWJG9COQiocR5wW/Kpzt3dLVCJzMPOZX7BVnzbxqLoPTAjMvcObrJ7XjAMpG3cEmvZu+KcDiMUhyG/A1TNjXsoO5Q7C9ql5WOc7bokC2OpvBsGCjH/FYiVYgZ6vv3eu9zaoAjeuNZb68FQvO4V333KewPymzqd+Nxav1T5w0aNLUUp9SoFvydeuyi4G/MsHjKWQtZrp07UbXvgHOQFXr+jnuiTC7JK4Y7+812Vmb60f+Pff+AOjzTJSE67rHyfzrvMyUtf7xNCZ3hQXWdYl8blB1lcH5vDvtG3AQ9Gpwp1ZtMXoddXKQUr15T2RYxkaMuRYKCMYeoMMfoNZ3EZ2yzri0TVcThv3yJxsKZy3fPi0y0+dASZllNvAQQ/DyTbcjmEafE8p6A5w9aPoMabpDiYC3kF+iEiwLWfPhtdMf5ieffuXM6ZWxiBJR/6qln98KUfe7dPt9G5ghN07IkIr6i5pxopMSN6LRmYCiWxD/SDyNgvmicX8jGX/+BA8QVQpIS7tcQK6SPKPGb8=
    on:
      tags: true
      branch: master
    skip_existing: true

  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token:
      secure: dJxMEtXCiiUHd9cx/G4hiIGeOcPw1bnoMeHodziVmRsSsnK+2Ukrsg9XSnT4SShKjdUyZqz8VBvLonHVpJJKDPe+ohl54CwsvDV1wpEu2xmY4UqsfRu4RAHL4x3YTvu5qBBcUXksBwXuQNd/XT1qzpXEiGHo3HXwq1MKMiXyp8FL50pu6KkskiY4xbQiKcDe9MRWextx9tLCiWX/iFPKfh4FbXlKNnKe0aOpnOHdt3S66IjG2haFp0RrHu5s8UtNIO3LGngApAw4bh1/RbrddHHKYoomqQkoFHoKqCENckRpozdKW9BATnqqVVwuFgvF4kIsDdVf+EkcArHq35HE7Oz/gt5SbqCLHxeoApfoLT45+n2BXTTcbzIFQPJ4wjQ75z2PangMsSmVaKP20AT+i2oHXMq+MemDrRVv8wAgDvoy3WIilw9dXHuT0gSN/WORN27NEB26rh1KhJjKIUFo1JBr2B9C0NKjuPI65XbfR/ePwPp732Q4lXhXhcAFcYiiiFvqi3I5NO2Q6/+40bEcCyxzbCfItlSEzd7TIlGD2RNv6ovAZQpp2jrGv+2q/XEbIAdGwhovKKGtKC1Prq9IsVungEueLuavgiCxfoKx+ZRHxiSMrvGX4Fl8DJxDbrizmhNxyU6qrLtMAl3VmRSoYheAKR4s3IBnyzfLQY9wafY=
    on:
      tags: true
      branch: master
    local-dir: docs/_build/html
    committer-from-gh: true