name: stytra
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - numba
  - pandas
  - pytables
  - git
  - ffmpeg
  - scikit-image
  - matplotlib
  - qt
  - opencv
  - av
  - pip:
    - stytra
