name: stytra_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - numba
  - pandas
  - pytables
  - git
  - ffmpeg
  - scikit-image
  - matplotlib
  - pyqt
  - opencv
  - av
  - pip:
    - stytra
